=== sunil-the-coder/javatraining/xml-fundamentals/src/studentdb.dtd
<!ELEMENT studentdb (student+)>
<!ELEMENT student (id,name,(email* | phone?))>
<!ELEMENT id (#PCDATA)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT email (#PCDATA)>
<!ELEMENT phone (#PCDATA)>
<!ATTLIST student fname #CDATA required>

=== sunil-the-coder/javatraining/xml-fundamentals/src/studentdb.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE studentdb SYSTEM "studentdb.dtd" >
<studentdb>
	<student fname="Sunil">
		<id>1</id>		
		<name>sunil</name>
		<email>sunil@gmail.com</email>
		<email>sunilpatil@gmail.com</email>
	</student>
	<student>
		<id>2</id>
		<name>ganesh</name>
		<phone>527895</phone>			
	</student>
	<student>
		<id>3</id>
		<name>anil</name>
	</student>
</studentdb>
